/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.possystem.view;

//import com.itextpdf.text.Document;
//import com.itextpdf.text.DocumentException;
//import com.itextpdf.text.pdf.PdfPTable;
//import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.possystem.controller.ItemController;
import lk.ijse.possystem.dto.ItemDTO;

/**
 *
 * @author Jaliya Roshen
 */
public class ManageItemForm extends javax.swing.JFrame {

    /**
     * Creates new form ManageItemForm
     */
    public ManageItemForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        qtyTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        codeTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        descTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        unitpriceTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ItemTable = new javax.swing.JTable();
        SearchButton = new javax.swing.JButton();
        SaveButton1 = new javax.swing.JButton();
        RemoveButton1 = new javax.swing.JButton();
        UpdateButton1 = new javax.swing.JButton();
        ViewButton1 = new javax.swing.JButton();
        PrintButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText(" Manage Item Form");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 60));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel2.setText(" Code");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 80, 30));
        getContentPane().add(qtyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 200, 30));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel3.setText(" Qty on Hand");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 100, 20));

        codeTextField1.setText(" ");
        getContentPane().add(codeTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 200, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel4.setText(" Description");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 80, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel5.setText(" Unit price");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 80, 20));

        descTextField1.setText(" ");
        getContentPane().add(descTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 200, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jLabel6.setText(" Unit price");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 80, 20));

        unitpriceTextField1.setText(" ");
        getContentPane().add(unitpriceTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 200, 30));

        ItemTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Description", " Unit Price", "Qty: on Hand"
            }
        ));
        jScrollPane1.setViewportView(ItemTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 720, 200));

        SearchButton.setText(" Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SearchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 80, 40));

        SaveButton1.setText(" Save");
        SaveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 80, 40));

        RemoveButton1.setText(" Remove");
        RemoveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 100, 80, 40));

        UpdateButton1.setText(" Update");
        UpdateButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 80, 40));

        ViewButton1.setText(" View ");
        ViewButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(ViewButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 80, 40));

        PrintButton1.setText(" Print");
        PrintButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(PrintButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        String code = codeTextField1.getText();
        ItemDTO itemDTO;
        try {
            itemDTO = ItemController.searchItem(code);
            if (itemDTO != null){
                
                descTextField1.setText(itemDTO.getDescription());
                unitpriceTextField1.setText(String.valueOf(itemDTO.getUnitPrice()));
                qtyTextField.setText(Integer.toString(itemDTO.getQtyOnHand()));
                
                
            }else{
                JOptionPane.showMessageDialog(this, "No such Item");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ManageItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void PrintButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButton1ActionPerformed
        
        
//        String path ="";
//        JFileChooser jfile = new JFileChooser();
//        jfile.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
//        
//        int x = jfile.showSaveDialog(this);
//        
//        if (x == JFileChooser.APPROVE_OPTION){
//            
//            path = jfile.getSelectedFile().getPath();
//            
//        }
//        
//        Document doc = new Document();
//        
//        try {
//            PdfWriter.getInstance(doc, new FileOutputStream(path+"ItemDetails.pdf"));
//            doc.open();
//            
//            PdfPTable table = new PdfPTable(4);
//            
//            table.addCell("Code");
//            table.addCell("Description");
//            table.addCell("Unit Price");
//            table.addCell("Quantity");
//            
//            
//            for (int i = 0; i < ItemTable.getRowCount(); i++) {
//                
//                String Code = ItemTable.getValueAt(i, 0).toString();
//                String Description = ItemTable.getValueAt(i, 1).toString();
//                String UnitPrice = ItemTable.getValueAt(i, 2).toString();
//                String Quantity = ItemTable.getValueAt(i, 3).toString();
//                
//                table.addCell(Code);
//                table.addCell(Description);
//                table.addCell(UnitPrice);
//                table.addCell(Quantity);
//                
//                
//                
//            }
//            
//            doc.add(table);
//            
//            JOptionPane.showMessageDialog(null, "PDF saved Successfully","ALERT MESSAGE",JOptionPane.WARNING_MESSAGE);
//            
//            
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (DocumentException ex) {
//            Logger.getLogger(ManageCustomer.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        
//        doc.close();
        
    }//GEN-LAST:event_PrintButton1ActionPerformed

    private void SaveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButton1ActionPerformed

        try {

            boolean isAdded = ItemController.addItem(new ItemDTO(codeTextField1.getText(),
                    descTextField1.getText(),
                    Double.parseDouble(unitpriceTextField1.getText()),
                    Integer.parseInt(qtyTextField.getText()))
            );
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Item Added ok");
            } else {
                JOptionPane.showMessageDialog(this, "Item Added Fail");
            }

        } catch (Exception ex) {
            Logger.getLogger( ManageItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SaveButton1ActionPerformed

    private void UpdateButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButton1ActionPerformed
        
        try {
            boolean isUpdate = ItemController.updateItem(new ItemDTO(codeTextField1.getText(), descTextField1.getText(),
                    Double.parseDouble(unitpriceTextField1.getText()), Integer.parseInt(qtyTextField.getText())));
            
            if (isUpdate){
                JOptionPane.showMessageDialog(this, "Update Success");
            }else{
                
                JOptionPane.showMessageDialog(this, "Update Fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(ManageItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UpdateButton1ActionPerformed

    private void RemoveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButton1ActionPerformed
         String code  = codeTextField1.getText();
         
        try {
            boolean isDeleted = ItemController.deleteItem(code);
            
            if (isDeleted){
                JOptionPane.showMessageDialog(this, "Delete Success");
            }else{
                JOptionPane.showMessageDialog(this, "Delete fail");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ManageItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_RemoveButton1ActionPerformed

    private void ViewButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewButton1ActionPerformed
         
        try {
            ArrayList<ItemDTO> items =  ItemController.getAllItems();
            DefaultTableModel dtm = (DefaultTableModel) ItemTable.getModel();
            dtm.setRowCount(0);
            for (ItemDTO item : items){
                
                Object [] ab ={item.getCode(), item.getDescription(), item.getUnitPrice(),item.getQtyOnHand()};
                dtm.addRow(ab);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(ManageItemForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ViewButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageItemForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageItemForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ItemTable;
    private javax.swing.JButton PrintButton1;
    private javax.swing.JButton RemoveButton1;
    private javax.swing.JButton SaveButton1;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UpdateButton1;
    private javax.swing.JButton ViewButton1;
    private javax.swing.JTextField codeTextField1;
    private javax.swing.JTextField descTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField qtyTextField;
    private javax.swing.JTextField unitpriceTextField1;
    // End of variables declaration//GEN-END:variables
}
